/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentattendance;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Sejal
 */
public class Manage extends javax.swing.JFrame {


    public Manage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subField = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        proceed = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        cb4 = new javax.swing.JComboBox();
        cb6 = new javax.swing.JComboBox();
        cb5 = new javax.swing.JComboBox();
        cb7 = new javax.swing.JComboBox();
        cb8 = new javax.swing.JComboBox();
        cb9 = new javax.swing.JComboBox();
        cb10 = new javax.swing.JComboBox();
        set = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        monday = new javax.swing.JRadioButton();
        tuesday = new javax.swing.JRadioButton();
        wednesday = new javax.swing.JRadioButton();
        thursday = new javax.swing.JRadioButton();
        friday = new javax.swing.JRadioButton();
        saturday = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectList.setModel(new DefaultListModel());
        subjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(subjectList);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("ADD SUBJECT");

        subField.setText(" ");
        subField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subFieldActionPerformed(evt);
            }
        });

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(add)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(subField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(add))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("<html><center>REMOVE SELECTED SUBJECT<center></html>");

        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(remove)
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proceed.setText(">>");
        proceed.setToolTipText("AFTER MAKING ALL THE CHANGES IN THE SUBJECT LIST, CLICK IT.");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proceed)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(proceed)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MANAGE SUBJECTS", jPanel1);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cb1.setModel(new DefaultComboBoxModel());
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setModel(new DefaultComboBoxModel());

        cb3.setModel(new DefaultComboBoxModel());

        cb4.setModel(new DefaultComboBoxModel());

        cb6.setModel(new DefaultComboBoxModel());

        cb5.setModel(new DefaultComboBoxModel());

        cb7.setModel(new DefaultComboBoxModel());

        cb8.setModel(new DefaultComboBoxModel());

        cb9.setModel(new DefaultComboBoxModel());

        cb10.setModel(new DefaultComboBoxModel());

        set.setText("SET");
        set.setToolTipText("TO BE CLICKED AFTER EVERY DAY'S ENTRY ");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });

        jLabel3.setText("1");

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("4");

        jLabel7.setText("5");

        jLabel8.setText("6");

        jLabel9.setText("7");

        jLabel10.setText("8");

        jLabel11.setText("9");

        jLabel12.setText("10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(set)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb1, 0, 73, Short.MAX_VALUE)
                            .addComponent(cb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb7, javax.swing.GroupLayout.Alignment.LEADING, 0, 79, Short.MAX_VALUE)
                            .addComponent(cb6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb10, 0, 80, Short.MAX_VALUE)
                            .addComponent(cb8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb9, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(monday);
        monday.setText("MONDAY");
        monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayActionPerformed(evt);
            }
        });

        buttonGroup1.add(tuesday);
        tuesday.setText("TUESDAY");

        buttonGroup1.add(wednesday);
        wednesday.setText("WEDNESDAY");

        buttonGroup1.add(thursday);
        thursday.setText("THURSDAY");

        buttonGroup1.add(friday);
        friday.setText("FRIDAY");

        buttonGroup1.add(saturday);
        saturday.setText("SATURDAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monday)
                    .addComponent(tuesday)
                    .addComponent(wednesday)
                    .addComponent(thursday)
                    .addComponent(friday)
                    .addComponent(saturday))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(monday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tuesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wednesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thursday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(friday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saturday)))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("MANAGE TIMETABLE", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subFieldActionPerformed



//  ......................................................................Subject List Addition and Deletion .....................................................................................................................
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      final DefaultListModel subList=(DefaultListModel)subjectList.getModel();
        subList.addElement(subField.getText());
        subField.setText("");
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
         int index = subjectList.getSelectedIndex();
         DefaultListModel subList=(DefaultListModel)subjectList.getModel();
         subList.remove(index);

    }//GEN-LAST:event_removeActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void mondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayActionPerformed



    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
      
        try
           {
                    Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost/attendance","root","root");
                    Statement stmt=con.createStatement();
                    stmt.execute("use attendance;");
                    // MONDAY
                     if(monday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='monday'" );
                                 }
                    
                    // TUESDAY
                     if(tuesday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='tuesday'" );                                 }
                    
                    // WEDNESDAY
                     if(wednesday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='wednesday'" );
                                 }
                    
                    // THURSDAY
                     if(thursday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='thursday'" );
                                }
                    
                    // FRIDAY
                     if(friday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='friday'" );                                
                                }
                    
                    // SATURDAY
                     if(saturday.isSelected()==true)
                                {
                                        stmt.execute("update timetable set "
                                                + "p1 ='" + cb1.getSelectedItem().toString() + "',"
                                                + "p2='" + cb2.getSelectedItem().toString() + "',"
                                                + "p3='" + cb3.getSelectedItem().toString() + "',"
                                                + "p4='" + cb4.getSelectedItem().toString() + "',"
                                                + "p5='" + cb5.getSelectedItem().toString() + "',"
                                                + "p6='" + cb6.getSelectedItem().toString() + "',"
                                                + "p7='" + cb7.getSelectedItem().toString() + "',"
                                                + "p8='" + cb8.getSelectedItem().toString() + "',"
                                                + "p9='" + cb9.getSelectedItem().toString() + "',"
                                                + "p10='" + cb10.getSelectedItem().toString()
                                                + "' \nwhere day='saturday'" );                                
                                }
                     
                    
                    
                    
                    
           }                
                        
           catch(Exception e)
            {
                    JOptionPane.showMessageDialog(null,e.getMessage());
            }     
        
    }//GEN-LAST:event_setActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
      DefaultListModel subList = (DefaultListModel) subjectList.getModel();
       try
           {
                    Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost/attendance","root","root");
                    Statement stmt=con.createStatement();
                    stmt.execute("use attendance;");
                    stmt.execute("DROP TABLE IF EXISTS subjects");
                    stmt.execute("CREATE TABLE IF NOT EXISTS subjects("
                            + "subname varchar(30) NOT NULL)");
                                    for (int i = 0; i < subList.getSize(); i++) {
                                                                     stmt.execute("insert into subjects values('"+subList.getElementAt(i)+"');");
                                                                     
                                    }
                    
           }
            catch(Exception e)
            {
                    JOptionPane.showMessageDialog(null,e.getMessage());
            }     
        DefaultComboBoxModel combo1 = (DefaultComboBoxModel) cb1.getModel();
        cb1.removeAllItems();
        cb1.setEditable(false);
         for (int i = 0; i < subList.getSize(); i++) {
            combo1.addElement(subList.getElementAt(i));
        }
        


        DefaultComboBoxModel combo2 = (DefaultComboBoxModel) cb2.getModel();
        cb2.removeAllItems();
        cb2.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo2.addElement(subList.getElementAt(i));
        }


        DefaultComboBoxModel combo3 = (DefaultComboBoxModel) cb3.getModel();
        cb3.removeAllItems();
        cb3.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo3.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo4 = (DefaultComboBoxModel) cb4.getModel();
        cb4.removeAllItems();
        cb4.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo4.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo5 = (DefaultComboBoxModel) cb5.getModel();
        cb5.removeAllItems();
        cb5.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo5.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo6 = (DefaultComboBoxModel) cb6.getModel();
        cb6.removeAllItems();
        cb6.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo6.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo7 = (DefaultComboBoxModel) cb7.getModel();
        cb7.removeAllItems();
        cb7.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo7.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo8 = (DefaultComboBoxModel) cb8.getModel();
        cb8.removeAllItems();
        cb8.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo8.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo9 = (DefaultComboBoxModel) cb9.getModel();
        cb9.removeAllItems();
        cb9.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo9.addElement(subList.getElementAt(i));
        }

        DefaultComboBoxModel combo10 = (DefaultComboBoxModel) cb10.getModel();
        cb10.removeAllItems();
        cb10.setEditable(false);
        for (int i = 0; i < subList.getSize(); i++) {
            combo10.addElement(subList.getElementAt(i));
        }
        
        
         try
           {
                    Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost/attendance","root","root");
                    Statement stmt=con.createStatement();
                    stmt.execute("use attendance;");
                    stmt.execute("CREATE TABLE IF NOT EXISTS timetable("
                            + "DAY varchar(20) , "
                            + "p1 varchar(30),"
                            + "p2 varchar(30),"
                            + "p3 varchar(30),"
                            + "p4 varchar(30),"
                            + "p5 varchar(30),"
                            + "p6 varchar(30),"
                            + "p7 varchar(30),"
                            + "p8 varchar(30),"
                            + "p9 varchar(30),"
                            + "p10 varchar(30) );" );
                    stmt.execute("INSERT INTO timetable VALUES"
                    + "('monday','','','','','','','','','',''),"
                    + "('tuesday','','','','','','','','','',''),"
                    + "('wednesday','','','','','','','','','',''),"
                    + "('thursday','','','','','','','','','',''),"
                    + "('friday','','','','','','','','','',''),"
                    + "('saturday','','','','','','','','','','');");
           }                
                        
           catch(Exception e)
            {
                    JOptionPane.showMessageDialog(null,e.getMessage());
            }     
    }//GEN-LAST:event_proceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
//         DefaultListModel subList;
//        static subList = (DefaultListModel)subjectList.getModel();
         



        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Manage and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb10;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JComboBox cb5;
    private javax.swing.JComboBox cb6;
    private javax.swing.JComboBox cb7;
    private javax.swing.JComboBox cb8;
    private javax.swing.JComboBox cb9;
    private javax.swing.JRadioButton friday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton monday;
    private javax.swing.JButton proceed;
    private javax.swing.JButton remove;
    private javax.swing.JRadioButton saturday;
    private javax.swing.JButton set;
    private javax.swing.JTextField subField;
    public static final javax.swing.JList subjectList = new javax.swing.JList();
    private javax.swing.JRadioButton thursday;
    private javax.swing.JRadioButton tuesday;
    private javax.swing.JRadioButton wednesday;
    // End of variables declaration//GEN-END:variables
}
